#!/bin/bash

set -o errexit
set -o nounset

mkdir -p /app/logs

until timeout 10 celery -A config.celery_app inspect ping; do
    >&2 echo "Celery workers not available"
done

echo 'Starting flower'


exec celery \
    -A config.celery_app \
    -b "${REDIS_URL}" \
    flower \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
