# Generated by Django 5.2.5 on 2026-09-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo pendiente')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('reason', models.TextField(blank=True, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Suma de todos los detalles: jornadas + abonos a préstamo.', max_digits=10, verbose_name='Valor total (bruto)')),
                ('payment_date', models.DateField(verbose_name='Fecha del pago')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voided_at', models.DateTimeField(blank=True, help_text='Fecha de anulación; nulo = pago vigente.', null=True, verbose_name='Anulado en')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLoanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor abonado')),
            ],
            options={
                'verbose_name': 'Detalle de pago (préstamo)',
                'verbose_name_plural': 'Detalles de pago (préstamos)',
            },
        ),
        migrations.CreateModel(
            name='PaymentWorkdayDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor aplicado')),
            ],
            options={
                'verbose_name': 'Detalle de pago (jornada)',
                'verbose_name_plural': 'Detalles de pago (jornadas)',
            },
        ),
    ]
