# Generated by Django 5.2.5 on 2026-09-05 06:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0002_seed_catalogs'),
        ('organizations', '0002_seed_organizations'),
        ('users', '0003_seed_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.PositiveIntegerField(verbose_name='Consecutivo')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('jornada_ids', models.JSONField(default=list)),
                ('detalle', models.JSONField(default=list)),
                ('subtotal_jornadas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_deuda_antes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('modo_descuento', models.CharField(choices=[('ninguno', 'Sin descuento'), ('total', 'Descontar total'), ('parcial', 'Descontar parcial')], default='ninguno', max_length=20)),
                ('monto_descontado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_deuda_despues', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pagada', 'Pagada')], default='pagada', max_length=20)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='organizations.organization')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='users.workerprofile')),
            ],
            options={
                'verbose_name': 'Liquidación',
                'verbose_name_plural': 'Liquidaciones',
                'ordering': ['-fecha_pago', '-consecutivo'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoDeuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepto', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('liquidacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='payments.liquidacion')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_creados', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='catalogs.tipomovimientodeuda')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='users.workerprofile')),
            ],
            options={
                'verbose_name': 'Movimiento de deuda',
                'verbose_name_plural': 'Movimientos de deuda',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLoanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_details', to='payments.movimientodeuda')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_details', to='payments.liquidacion')),
            ],
            options={
                'verbose_name': 'Detalle loan-liquidación',
                'verbose_name_plural': 'Detalles loan-liquidación',
            },
        ),
        migrations.CreateModel(
            name='PaymentWorkdayDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workday_id', models.BigIntegerField(help_text='ID del Workday. Sin FK por dependencia circular workdays↔payments.')),
                ('applied_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workday_details', to='payments.liquidacion')),
            ],
            options={
                'verbose_name': 'Detalle workday-liquidación',
                'verbose_name_plural': 'Detalles workday-liquidación',
            },
        ),
        migrations.AddIndex(
            model_name='liquidacion',
            index=models.Index(fields=['organization', 'consecutivo'], name='payments_li_organiz_59ec5d_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidacion',
            index=models.Index(fields=['worker'], name='payments_li_worker__953053_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidacion',
            index=models.Index(fields=['fecha_pago'], name='payments_li_fecha_p_eaf74a_idx'),
        ),
        migrations.AddConstraint(
            model_name='liquidacion',
            constraint=models.UniqueConstraint(fields=('organization', 'consecutivo'), name='unique_consecutivo_per_org'),
        ),
        migrations.AddIndex(
            model_name='movimientodeuda',
            index=models.Index(fields=['worker', 'fecha'], name='payments_mo_worker__585a01_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientodeuda',
            index=models.Index(fields=['liquidacion'], name='payments_mo_liquida_5004b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentloandetail',
            constraint=models.UniqueConstraint(fields=('payment', 'loan'), name='unique_payment_loan'),
        ),
    ]
