# Generated by Django 5.2.5 on 2026-09-06 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('payments', '0001_initial'),
        ('users', '0001_initial'),
        ('workdays', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='catalogs.loanstatus', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='loan',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='users.workerprofile', verbose_name='Trabajador'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='catalogs.paymentmethod', verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='payment',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_voided', to=settings.AUTH_USER_MODEL, verbose_name='Anulado por'),
        ),
        migrations.AddField(
            model_name='payment',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='users.workerprofile', verbose_name='Trabajador'),
        ),
        migrations.AddField(
            model_name='paymentloandetail',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_details', to='payments.loan', verbose_name='Préstamo'),
        ),
        migrations.AddField(
            model_name='paymentloandetail',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_details', to='payments.payment', verbose_name='Pago'),
        ),
        migrations.AddField(
            model_name='paymentworkdaydetail',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workday_details', to='payments.payment', verbose_name='Pago'),
        ),
        migrations.AddField(
            model_name='paymentworkdaydetail',
            name='workday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_details', to='workdays.workday', verbose_name='Jornada'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['worker', 'date'], name='payments_lo_worker__4513b1_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status'], name='payments_lo_status__fd7c07_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['worker', 'payment_date'], name='payments_pa_worker__acefca_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='payments_pa_payment_33e537_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['voided_at'], name='payments_pa_voided__f97ad4_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentloandetail',
            constraint=models.UniqueConstraint(fields=('payment', 'loan'), name='unique_payment_loan'),
        ),
        migrations.AddConstraint(
            model_name='paymentworkdaydetail',
            constraint=models.UniqueConstraint(fields=('payment', 'workday'), name='unique_payment_workday'),
        ),
    ]
