# Generated by Django 5.2.5 on 2026-09-05 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Método de pago',
                'verbose_name_plural': 'Métodos de pago',
                'ordering': ['order', 'name'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active'], name='catalogs_pa_is_acti_600a50_idx')],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Estado de pago',
                'verbose_name_plural': 'Estados de pago',
                'ordering': ['order', 'name'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active'], name='catalogs_pa_is_acti_37ddb9_idx')],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='TipoMovimientoDeuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('affects_balance', models.BooleanField(default=True, help_text='Si True, suma al saldo de deuda; si False, resta.', verbose_name='Afecta saldo')),
            ],
            options={
                'verbose_name': 'Tipo de movimiento de deuda',
                'verbose_name_plural': 'Tipos de movimiento de deuda',
                'ordering': ['order', 'name'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active'], name='catalogs_ti_is_acti_42d02a_idx')],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='WorkdayType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Factor')),
                ('organization', models.ForeignKey(blank=True, help_text='Vacío = catálogo global compartido por todas las organizaciones.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workday_types', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Tipo de jornada',
                'verbose_name_plural': 'Tipos de jornada',
                'ordering': ['order', 'name'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active'], name='catalogs_wo_is_acti_280650_idx')],
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
