# Generated by Django 5.2.5 on 2026-09-06 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_seed_organizations'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Estado de préstamo',
                'verbose_name_plural': 'Estados de préstamo',
                'ordering': ['order', 'name'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active'], name='catalogs_lo_is_acti_ea5ec4_idx')],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_loan_status')],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Método de pago',
                'verbose_name_plural': 'Métodos de pago',
                'ordering': ['order', 'name'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active'], name='catalogs_pa_is_acti_600a50_idx')],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_payment_method')],
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Estado de pago',
                'verbose_name_plural': 'Estados de pago',
                'ordering': ['order', 'name'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active'], name='catalogs_pa_is_acti_37ddb9_idx')],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_payment_status')],
            },
        ),
        migrations.CreateModel(
            name='WorkdayType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('factor', models.DecimalField(decimal_places=2, default='1.00', max_digits=4, verbose_name='Factor')),
                ('organization', models.ForeignKey(blank=True, help_text='Vacío = catálogo global compartido por todas las organizaciones.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workday_types', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Tipo de jornada',
                'verbose_name_plural': 'Tipos de jornada',
                'ordering': ['order', 'name'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active'], name='catalogs_wo_is_acti_280650_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='unique_workday_type_per_org')],
            },
        ),
    ]
