# Generated by Django 5.2.5 on 2026-09-05 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0002_seed_catalogs'),
        ('users', '0003_seed_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('applied_rate', models.DecimalField(decimal_places=2, help_text='Valor realmente pagado este día (puede diferir de la tarifa vigente).', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('liquidacion_id', models.BigIntegerField(blank=True, help_text='ID de la liquidación que bloquea esta jornada. Sin FK por dependencia circular workdays↔payments.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workdays_created', to=settings.AUTH_USER_MODEL)),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workdays', to='catalogs.paymentstatus')),
                ('workday_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workdays', to='catalogs.workdaytype')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workdays', to='users.workerprofile')),
            ],
            options={
                'verbose_name': 'Jornada',
                'verbose_name_plural': 'Jornadas',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['worker', 'date'], name='workdays_wo_worker__e59e91_idx'), models.Index(fields=['payment_status'], name='workdays_wo_payment_6d2636_idx'), models.Index(fields=['date'], name='workdays_wo_date_ed269a_idx')],
                'constraints': [models.UniqueConstraint(fields=('worker', 'date'), name='unique_workday_per_worker_date')],
            },
        ),
    ]
