# Generated by Django 5.2.5 on 2026-09-06 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('applied_rate', models.DecimalField(decimal_places=2, help_text='Valor realmente pagado este día; puede diferir de la tarifa vigente.', max_digits=10, verbose_name='Valor aplicado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workdays_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workdays', to='catalogs.paymentstatus', verbose_name='Estado de pago')),
                ('workday_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workdays', to='catalogs.workdaytype', verbose_name='Tipo de jornada')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workdays', to='users.workerprofile', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Jornada',
                'verbose_name_plural': 'Jornadas',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['worker', 'date'], name='workdays_wo_worker__e59e91_idx'), models.Index(fields=['payment_status'], name='workdays_wo_payment_6d2636_idx'), models.Index(fields=['date'], name='workdays_wo_date_ed269a_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkerRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('valid_from', models.DateField(verbose_name='Vigente desde')),
                ('valid_until', models.DateField(blank=True, help_text='Vacío = vigente de forma indefinida.', null=True, verbose_name='Vigente hasta')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='users.workerprofile', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Tarifa de trabajador',
                'verbose_name_plural': 'Tarifas de trabajador',
                'ordering': ['-valid_from'],
                'indexes': [models.Index(fields=['worker', 'valid_from'], name='workdays_wo_worker__6be8d4_idx')],
            },
        ),
    ]
